In [1]:
import numpy as np

In [2]:
# Creating Numpy Array

In [3]:
my_list = [1, 2, 3]

In [5]:
#np.array([1, 2, 3]);
x = np.array(my_list)

In [6]:
type(x)

numpy.ndarray

In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
y = np.array(my_matrix)

In [10]:
type(y)

numpy.ndarray

In [11]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [13]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [14]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
type(1)

int

In [17]:
type(1.0)

float

In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [20]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.linspace(0, 10, 12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand(3, 5)

array([[0.43760798, 0.83577058, 0.94101189, 0.28445621, 0.79758271],
       [0.95445695, 0.15270298, 0.22292623, 0.88159585, 0.35528437],
       [0.95856175, 0.7011926 , 0.75588801, 0.62040859, 0.60257906]])

In [30]:
# normal
np.random.randn(5, 4)

array([[ 0.99656165, -0.74226171, -1.12648414,  2.15311026],
       [ 0.45214538, -0.46110308, -0.65283756, -0.96879434],
       [ 1.07598935,  0.42854418, -0.28368764,  0.32462054],
       [-2.20315803,  0.51635494,  2.0249729 ,  0.90103584],
       [-1.24892378, -0.59972655,  0.6076915 ,  1.23116915]])

In [31]:
np.random.randint(1, 100, 10)

array([80, 50, 11, 81, 14, 33, 45, 89, 93, 71])

In [32]:
arr = np.arange(25)
ran_arr = np.random.randint(0, 50, 10)

In [33]:
ran_arr

array([37, 39, 47,  5, 26, 47, 42, 28, 20, 46])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.reshape(5, 5) # 5 * 5 = 25

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
arr.shape

(25,)

In [40]:
arr.reshape(5, 5).shape

(5, 5)

In [41]:
ran_arr.shape

(10,)

In [43]:
ran_arr.max()

47

In [44]:
# the index of maximum value
ran_arr.argmax()

2

In [45]:
# the index of minimum value
ran_arr.argmin()

3

In [46]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [47]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [48]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [49]:
arr / arr

<ipython-input-49-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [50]:
1 / arr

<ipython-input-50-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667])

In [51]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [52]:
np.max(arr)

24

In [53]:
np.log(arr)

<ipython-input-53-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [54]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])