In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr[9]

9

In [4]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [5]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [6]:
arr[:4] = 100

In [7]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [8]:
arr = np.arange(0, 11)

In [9]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_copy = arr.copy()

In [15]:
arr_copy[:] = 200

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [18]:
# mat[row, col]
# mat[row][col]

In [19]:
mat = np.array([[5, 10, 15],[20, 25, 30],[35, 40, 45]])

In [20]:
mat[0]

array([ 5, 10, 15])

In [21]:
mat[1][1]

25

In [22]:
mat[1, 1]

25

In [24]:
mat[:2, 1:]

array([[10, 15],
       [25, 30]])

In [25]:
# Conditional Selection
arr = np.arange(1, 11)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])